spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shetuan?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181
  servlet:
    session:
      cookie:
        max-age: 86400

file:
  upload:
    path: "src/main/webapp/upload/"

interceptor:
  path:
    exclude: "/index.jsp"
